'use strict';

/**
 * Runtime installer for the self-contained hook system.
 *
 * The monitoring logic now lives in a standalone Node runtime (src/hooks/runner.js)
 * that depends only on Node built-ins. This service copies that runtime into
 * ~/.claude/session-monitor/runner.js and writes three thin bash wrappers into
 * ~/.claude/hooks — one per Claude Code hook event (SessionStart, PreToolUse,
 * SessionEnd). Each wrapper bakes in the ABSOLUTE runner path and simply execs
 * `node <runner> <event>`, failing open when node is unavailable.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');

// Paths are derived from os.homedir() at load time so tests can spy on it.
const RUNTIME_DIR = path.join(os.homedir(), '.claude', 'session-monitor');
const RUNNER_PATH = path.join(RUNTIME_DIR, 'runner.js');
const HOOK_DIR = path.join(os.homedir(), '.claude', 'hooks');

// Source runtime shipped with the package (src/hooks/runner.js).
const SOURCE_RUNNER_PATH = path.join(__dirname, '..', 'hooks', 'runner.js');

// One wrapper per hook event: [event key, wrapper filename, runner event arg].
const WRAPPER_SPECS = [
  { event: 'SessionStart', file: 'csm-session-start.sh', arg: 'sessionstart' },
  { event: 'PreToolUse', file: 'csm-pretooluse.sh', arg: 'pretooluse' },
  { event: 'SessionEnd', file: 'csm-session-end.sh', arg: 'sessionend' },
];

const WRAPPERS = WRAPPER_SPECS.reduce((acc, spec) => {
  acc[spec.event] = path.join(HOOK_DIR, spec.file);
  return acc;
}, {});

/**
 * Build the bash wrapper content for a given runner event argument.
 * The absolute RUNNER_PATH is baked in so the wrapper does not rely on $HOME
 * at runtime. `exec` hands stdin and the exit code straight through to node.
 * @param {string} eventArg sessionstart | pretooluse | sessionend
 * @returns {string} the wrapper script text
 */
function wrapperContent(eventArg) {
  return (
    '#!/usr/bin/env bash\n' +
    '# Auto-generated by claude-session-monitor. Do not edit by hand.\n' +
    'command -v node >/dev/null 2>&1 || exit 0\n' +
    `exec node "${RUNNER_PATH}" ${eventArg}\n`
  );
}

/**
 * Install the self-contained runtime and its three bash wrappers.
 *  1. Create RUNTIME_DIR and HOOK_DIR (mode 0700).
 *  2. Copy the package runner into RUNNER_PATH (mode 0755).
 *  3. Write each wrapper into HOOK_DIR (mode 0755).
 * @returns {{ runnerPath: string, wrappers: object }} installed locations
 */
function installRuntime() {
  fs.mkdirSync(RUNTIME_DIR, { recursive: true, mode: 0o700 });
  fs.mkdirSync(HOOK_DIR, { recursive: true, mode: 0o700 });

  fs.copyFileSync(SOURCE_RUNNER_PATH, RUNNER_PATH);
  fs.chmodSync(RUNNER_PATH, 0o755);

  for (const spec of WRAPPER_SPECS) {
    const target = WRAPPERS[spec.event];
    fs.writeFileSync(target, wrapperContent(spec.arg), { mode: 0o755 });
    // writeFileSync honors mode only on creation; enforce it explicitly.
    fs.chmodSync(target, 0o755);
  }

  return { runnerPath: RUNNER_PATH, wrappers: WRAPPERS };
}

/**
 * Best-effort removal of the installed runtime and wrappers.
 * @returns {boolean} true if at least one file was removed
 */
function removeRuntime() {
  let removed = false;
  const targets = [RUNNER_PATH, ...Object.values(WRAPPERS)];
  for (const target of targets) {
    try {
      if (fs.existsSync(target)) {
        fs.unlinkSync(target);
        removed = true;
      }
    } catch (_e) {
      /* best-effort: never throw during removal */
    }
  }
  return removed;
}

module.exports = {
  RUNTIME_DIR,
  RUNNER_PATH,
  HOOK_DIR,
  WRAPPERS,
  installRuntime,
  removeRuntime,
};
