#!/usr/bin/env bash
#
# Auto-generated by claude-session-monitor. Do not edit by hand.
#
# Claude Code PreToolUse hook: detects concurrent Claude sessions across
# machines by maintaining a shared lock file and notifying a Telegram group.
# Fires before EVERY tool call, so it is deliberately quiet: it only notifies
# on a NEW session or a genuine cross-machine CONFLICT.
#
# Exit codes:
#   0  allow the tool call (normal / same-session / new-session)
#   2  block the tool call (another machine holds an active session)

set -u

# ---------------------------------------------------------------------------
# Configuration (substituted at install time)
# ---------------------------------------------------------------------------
BOT_TOKEN="{{BOT_TOKEN}}"
GROUP_ID="{{GROUP_ID}}"
TIMEOUT="{{TIMEOUT}}"
HISTORY_LOG="{{HISTORY_PATH}}"

# ---------------------------------------------------------------------------
# Runtime variables
# ---------------------------------------------------------------------------
LOCK="/tmp/claude-session-${USER:-$(whoami)}.lock"
MACHINE="$(hostname)"

# Guard against a missing `date` binary: fall back to 0 / empty timestamps.
if command -v date >/dev/null 2>&1; then
  NOW="$(date +%s)"
  ISO="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
else
  NOW="0"
  ISO="unknown"
fi

# Ensure TIMEOUT and NOW are numeric; default TIMEOUT to 30 minutes if not.
case "$TIMEOUT" in
  ''|*[!0-9]*) TIMEOUT=1800 ;;
esac
case "$NOW" in
  ''|*[!0-9]*) NOW=0 ;;
esac

# ---------------------------------------------------------------------------
# send_telegram: best-effort notification. NEVER blocks or fails the hook.
# Usage: send_telegram "<html-message>"
# ---------------------------------------------------------------------------
send_telegram() {
  local message="$1"

  # If curl is unavailable, silently skip notification (lock is still managed).
  if ! command -v curl >/dev/null 2>&1; then
    return 0
  fi

  # --max-time caps the request; failures are swallowed so Claude is never
  # blocked by a slow or unreachable Telegram API.
  curl --max-time 10 -s \
    "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
    --data-urlencode "chat_id=${GROUP_ID}" \
    --data-urlencode "text=${message}" \
    --data-urlencode "parse_mode=HTML" \
    >/dev/null 2>&1 || true

  return 0
}

# ---------------------------------------------------------------------------
# append_history: best-effort append to the history log (tab-separated).
# Usage: append_history "<event>" "<detail>"
# ---------------------------------------------------------------------------
append_history() {
  local event="$1"
  local detail="$2"
  printf '%s\t%s\t%s\t%s\n' "$ISO" "$event" "$MACHINE" "$detail" >>"$HISTORY_LOG" 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# write_lock: (re)write the lock file with this machine + current timestamp.
# ---------------------------------------------------------------------------
write_lock() {
  printf '%s\n%s\n' "$MACHINE" "$NOW" >"$LOCK" 2>/dev/null || true
}

# Make sure the history directory exists (best-effort).
mkdir -p "$(dirname "$HISTORY_LOG")" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Main logic
# ---------------------------------------------------------------------------
if [ -f "$LOCK" ]; then
  LAST_MACHINE=""
  LAST_TS=""
  # Read the two lines defensively.
  { IFS= read -r LAST_MACHINE; IFS= read -r LAST_TS; } <"$LOCK" 2>/dev/null || true

  # Sanitize the stored timestamp to an integer.
  case "$LAST_TS" in
    ''|*[!0-9]*) LAST_TS=0 ;;
  esac

  DELTA=$((NOW - LAST_TS))

  if [ "$LAST_MACHINE" != "$MACHINE" ] && [ "$DELTA" -lt "$TIMEOUT" ]; then
    # ---- CONFLICT: another machine holds an active session -----------------
    MINUTES=$((DELTA / 60))
    send_telegram "⚠️ <b>Claude session conflict</b>
Machine <b>${MACHINE}</b> tried to start while <b>${LAST_MACHINE}</b> has been active (${MINUTES} min ago).
The tool call on <b>${MACHINE}</b> was <b>blocked</b>."
    append_history "CONFLICT" "conflict with ${LAST_MACHINE}"
    echo "claude-session-monitor: BLOCKED — an active Claude session is already running on '${LAST_MACHINE}' (${MINUTES} min ago). Stop that session before continuing on '${MACHINE}'." >&2
    exit 2
  fi

  if [ "$LAST_MACHINE" = "$MACHINE" ] && [ "$DELTA" -lt "$TIMEOUT" ]; then
    # ---- Same active session: just refresh the lock, stay silent -----------
    write_lock
    exit 0
  fi

  # Otherwise the lock is stale (DELTA >= TIMEOUT) -> fall through to new session.
fi

# ---------------------------------------------------------------------------
# New session branch (no lock, or stale lock)
# ---------------------------------------------------------------------------
write_lock
append_history "START" "new session"
send_telegram "✅ <b>Claude session started</b> on <b>${MACHINE}</b>."
exit 0
